version: '3.8'

services:

  ## Application service
  carp-wearables-service:
    container_name: carp-wearables-service-${PROFILE:-local}
    build:
      context: ../..
      dockerfile: ../docker/Dockerfile
    ports:
      - 8444:8444
    expose:
      - 8444
    environment:
      - profile=${PROFILE:-local}
    networks:
      - cans
    depends_on:
      - rabbitmq-common
      - postgres

  # Common RabbitMQ
  rabbitmq-common:
    container_name: carp-rabbitmq-${PROFILE:-local}
    hostname: rabbitmq-common
    image: rabbitmq:4-management
    ports:
      - 5673:5672
      - 15673:15672
      - 15693:15692
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
      - ./config/rabbit/definitions.json:/etc/rabbitmq/definitions.json
      - ./config/rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - cans
    restart: unless-stopped

  # PostgreSQL
  postgres:
    container_name: carp-postgres-${PROFILE:-local}
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gardener}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cans
    restart: unless-stopped

networks:
  cans:
    driver: bridge

volumes:
  postgres_data:
    name: carp_postgres_data_${PROFILE:-local}
  rabbitmq_data:
    name: carp_rabbitmq_data_${PROFILE:-local}
