[versions]
kotlin = "2.0.21"
junit = "5.11.4"
shadow = "8.0.0"
slf4j = "2.0.17"
logback = "1.5.13"
jackson = "2.20.0"
mockitoKotlin = "5.4.0"
detekt = "1.23.8"
ktlintGradle = "13.1.0"

ktor = "3.0.3"

mongodb = "5.1.2"


# Coroutines
kotlinx_coroutines = "1.9.0"
# If you keep a native Netty for mac, pin it explicitly (or align to Vert.x BOM)
netty = "4.1.67.Final"

[libraries]
guava = { module = "com.google.guava:guava", version = "32.0.1-jre" }
scribejava = { module = "com.github.scribejava:scribejava-core", version = "8.3.3" }

jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-jsr310        = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

slf4j-api    = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback      = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

rabbitmq     = { module = "com.rabbitmq:amqp-client", version = "5.18.0" }
netty-osx    = { module = "io.netty:netty-resolver-dns-native-macos", version.ref = "netty" }

kotlin-stdlib  = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

mockito-kotlin        = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }

# Ktor
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson-jvm", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx_coroutines" }
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }


[plugins]
kotlin-jvm            = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization  = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow                = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
application           = { id = "application" }  # core plugin, no version

detekt                = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint                = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
